'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'

function api(path: string) { return `/api${path}` }
type Detail = { store_id?: any; narrative?: string; citations?: {type?:any;id?:any;detail?:any}[]; methodology?: {chunk_id?:any;title?:any;part?:any;score?:any}[]; guard?: Record<string,any> }
export default function StoreDetail({ params }: { params: Promise<{ id: string }> }) { const [id,setId]=useState(''); const [data,setData]=useState<Detail|null>(null); const [error,setError]=useState('')
 useEffect(()=>{params.then(({id})=>{setId(id);fetch(api(`/why/${id}`),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setError('This store detail could not be loaded.'))})},[params])
 return <><div className="topline"/><main className="shell"><nav className="nav"><Link href="/" className="brand"><span className="mark">RD</span>Retail Decision Board</Link><div className="navlinks"><Link href="/">Overview</Link><span>Read-only view</span></div></nav><section className="hero"><div><Link href="/" className="back">← Back to board</Link><div className="eyebrow" style={{marginTop:24}}>Store detail</div><h1>Store {data?.store_id || id}</h1><p>Evidence and explanation from the decision API.</p></div></section>{error&&<div className="error">{error}</div>}{!data&&!error?<div className="loading">Loading store evidence…</div>:data&&<div className="detail-grid"><article className="panel"><h2 className="section-title">Why this store?</h2><p className="narrative" style={{marginTop:18}}>{data.narrative || 'No narrative was returned.'}</p><div className="chips">{data.citations?.map((citation,i)=><span className="chip" key={i}>{display(citation.type)} · {display(citation.id)} · {display(citation.detail)}</span>)}</div></article><aside className="panel"><h2 className="section-title">Grounding</h2><div className="chips">{Object.entries(data.guard || {}).map(([key,value])=><span className="badge available" key={key}>{key}: {String(value)}</span>)}</div>{data.methodology?.length ? <><h3 style={{marginTop:26,fontSize:13}}>Methodology</h3><div className="chips">{data.methodology.map((item,i)=><span className="chip" key={i}>{display(item.title)} · {display(item.part)}</span>)}</div></> : null}</aside></div>}</main><footer className="shell footer"><span>© 2026 retail decision intelligence agent · dunnhumby</span><span>Connection is read-only</span></footer></> }
function display(value:any){return value===null||value===undefined||value===''?'—':String(value)}
