'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'

const ORDER = ['needs_intervention', 'working_well', 'recovering', 'watch', 'insufficient_data']
const labels: Record<string,string> = { needs_intervention:'Needs intervention', working_well:'Working well', recovering:'Recovering', watch:'Watch', insufficient_data:'Insufficient data' }

type Row = Record<string, any>
type Board = { total_stores?: any; counts?: Record<string, any>; buckets?: Record<string, Row[]> }

function api(path: string) { return `/api${path}` }
function display(value: any) { return value === null || value === undefined || value === '' ? '—' : String(value) }
function Forecast({ status }: { status: any }) { const value = String(status || 'NO_DATA').toUpperCase(); return <span className={`badge ${value === 'AVAILABLE' ? 'available' : value === 'ERROR' ? 'error' : 'no-data'}`}>{value === 'ERROR' ? 'feed stale' : value}</span> }
function Metric({ label, value }: { label: string; value: any }) { return <div><div className="metric-label">{label}</div><div className="metric-value">{display(value)}</div></div> }
function DecisionCard({ row }: { row: Row }) { if (!row.default_action) return null; return <div className="decision"><div><div className="decision-label">Default action</div><div className="decision-value">{display(row.default_action)}</div></div><div><div className="decision-label">Fallback action</div><div className="decision-value">{display(row.fallback_action)}</div></div><div><div className="decision-label">Risk / cost of inaction</div><div className="decision-value">{display(row.risk)}</div><div className="decision-note">{display(row.cost_of_inaction)}</div></div><div className="decision-foot">Human decision required · decide at /ui/approvals</div></div> }
function StoreRow({ row }: { row: Row }) { return <div className="row"><div><Link href={`/store/${row.store_id}`} className="store-id">{display(row.store_id)}</Link><div className="store-label">store</div></div><div><div className="recommendation">{display(row.recommendation)}</div><div className="reason">{display(row.reason)}</div></div><div className="metrics"><Metric label="Health" value={row.store_health_score}/><Metric label="Recovery" value={row.recovery_pct}/><Metric label="Days left" value={row.days_remaining}/></div><div className="metrics"><Metric label="Uplift" value={row.uplift_pct}/><Metric label="Did uplift" value={row.did_uplift_pct}/><Metric label="Causal" value={row.causal_state}/></div><div className="forecast"><Forecast status={row.forecast_status}/></div><DecisionCard row={row}/></div> }

export default function BoardPage() { const [board,setBoard]=useState<Board|null>(null); const [error,setError]=useState(''); const [waking,setWaking]=useState(false)
 const load=useCallback(async()=>{ try { const response=await fetch(api('/board'),{cache:'no-store'}); if(response.status===502||response.status===504){setWaking(true);setTimeout(async()=>{ try { const retry=await fetch(api('/board'),{cache:'no-store'}); if(!retry.ok) throw new Error('Retry failed'); setBoard(await retry.json());setError('');setWaking(false) } catch { setError('The board could not be loaded. The service may still be waking up.');setWaking(false) } },30000);return} if(!response.ok) throw new Error('Unable to load board'); setBoard(await response.json());setError('');setWaking(false) } catch { setError('The board could not be loaded. Check the API connection and try again.');setWaking(false) } },[])
 useEffect(()=>{load();const timer=setInterval(load,60000);return()=>{clearInterval(timer)}},[load])
 return <><div className="topline"/><main className="shell"><nav className="nav"><Link href="/" className="brand"><span className="mark">RD</span>Retail Decision Board</Link><div className="navlinks"><Link href="/">Overview</Link><span>Read-only view</span></div></nav><section className="hero"><div><div className="eyebrow">Stakeholder intelligence</div><h1>Know where to focus.</h1><p>Decision context across every participating store.</p></div><div className="sync">Live API view<br/><strong>Refreshes every 60 seconds</strong></div></section>{waking&&<div className="error">Service waking up… retrying once in 30 seconds.</div>}{error&&<div className="error">{error}</div>}{!board&&!error?<div className="loading">Loading the latest board…</div>:board&&<><section className="kpis"><div className="kpi"><div className="kpi-label">Total stores</div><div className="kpi-value kpi-accent">{display(board.total_stores)}</div></div>{ORDER.map(key=><div className="kpi" key={key}><div className="kpi-label">{labels[key]}</div><div className="kpi-value">{display(board.counts?.[key])}</div></div>)}</section><section className="section"><div className="section-head"><h2 className="section-title">Store portfolio</h2><span className="section-count">All values served by the API</span></div>{ORDER.map(bucket=><div className="bucket" key={bucket}><div className="bucket-head"><span className="bucket-dot"/><span className="bucket-title">{labels[bucket]}</span><span className="section-count">{board.buckets?.[bucket]?.length || 0} stores</span></div>{board.buckets?.[bucket]?.length ? board.buckets[bucket].map((row,i)=><StoreRow row={row} key={`${row.store_id}-${i}`}/>) : <div className="empty">No stores in this bucket.</div>}</div>)}</section></>}</main><footer className="shell footer"><span>© 2026 retail decision intelligence agent · dunnhumby</span><span>Connection is read-only</span></footer></> }
