#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Render deployment of the Retail Decision Intelligence Agent.
# One run takes ~15 minutes (most of it waiting for the first Docker build).
# Values this wizard captures land in .env.local (local-only, gitignored).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"

banner "Render deployment — Retail Decision Intelligence Agent"

# ── Stage 1: Render account ────────────────────────────────────────────────
stage "Render account"
say "The agent deploys from your GitHub repo via the render.yaml blueprint."
step "Sign in (GitHub login is easiest) or create a free account."
step "Have a payment card ready: the blueprint uses the Starter plan + a disk"
step "(~\$7.25/mo total). Free tier spins down after ~15 min and cannot mount"
step "the disk — the audit trail would reset on every deploy."
open_url "https://dashboard.render.com/register"
pause "Signed in to the Render dashboard?"

# ── Stage 2: collect the values the dashboard will ask for ────────────────
stage "Credentials and settings"
say "These are written to $ENV_FILE (local-only) and pasted into the"
say "Render prompts at stage 3. Press Enter to keep any existing value."
say ""
# Reuse the token already in $ENV_FILE when re-running: rotating it here would
# silently break the token already configured in the Render dashboard, and this
# wizard tells the human to re-run after a failed first deploy.
TOKEN=$(_existing APPROVAL_AUTH_TOKEN || true)
if [[ -z "$TOKEN" ]]; then
  TOKEN=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  printf '  %sGenerated approval token (copy this into the dashboard later):%s\n' "$BOLD" "$RESET"
  printf '  %s%s%s\n' "$GREEN" "$TOKEN" "$RESET"
  write_env APPROVAL_AUTH_TOKEN "$TOKEN"
else
  printf '  %sKeeping the approval token already in %s.%s\n' "$DIM" "$ENV_FILE" "$RESET"
fi

ask_secret APPROVAL_TOKENS "APPROVAL_TOKENS (named approvers, tok:user:role; Enter to skip):"
if [[ -n "${APPROVAL_TOKENS:-}" ]]; then write_env APPROVAL_TOKENS "$APPROVAL_TOKENS"; fi

ask FORECAST_API_URL "Forecast API URL [https://retail-forecast-api-7sue.onrender.com/]:"
FORECAST_API_URL="${FORECAST_API_URL:-https://retail-forecast-api-7sue.onrender.com/}"
write_env FORECAST_API_URL "$FORECAST_API_URL"

ask CAMPAIGN_AUDIT_API_URL "Campaign Audit API URL (Enter to skip):"
[[ -n "${CAMPAIGN_AUDIT_API_URL:-}" ]] && write_env CAMPAIGN_AUDIT_API_URL "$CAMPAIGN_AUDIT_API_URL"

if confirm "Enable the LLM layers on Render (advisory + narrative)?"; then
  say "Provider facts: LLM_PROVIDER=openai_compat, LLM_BASE_URL is your Groq or"
  say "other OpenAI-compatible endpoint; LLM_API_KEY stays hidden."
  ask LLM_BASE_URL "LLM_BASE_URL [https://api.groq.com/openai/v1]:"
  LLM_BASE_URL="${LLM_BASE_URL:-https://api.groq.com/openai/v1}"
  write_env LLM_BASE_URL "$LLM_BASE_URL"
  write_env LLM_PROVIDER "openai_compat"
  ask_secret LLM_API_KEY "LLM_API_KEY (Enter keeps the value already in $ENV_FILE):"
  [[ -n "${LLM_API_KEY:-}" ]] && write_env LLM_API_KEY "$LLM_API_KEY"
  ask_secret ANTHROPIC_API_KEY "ANTHROPIC_API_KEY (only for the anthropic provider; Enter to skip):"
  [[ -n "${ANTHROPIC_API_KEY:-}" ]] && write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
else
  say "LLM layers stay off on Render (advisory degrades to the deterministic engine)."
fi

say ""
say "DATABASE_URL stays empty: the service uses embedded SQLite on its disk."
pause "Values collected?"

# ── Stage 3: blueprint apply ───────────────────────────────────────────────
stage "Blueprint apply"
say "Render reads render.yaml from the repo and asks you to fill every value"
say "marked 'sync: false'. Paste from the list above (also in $ENV_FILE)."
open_url "https://render.com/deploy?repo=https://github.com/ashishkumar-ds/retail-decision-intelligence-agent"
step "New → Blueprint → pick this repo (grant access if asked)."
step "Render shows the resources: one web service + one 1GB disk."
step "Fill each prompted env var with the matching value from $ENV_FILE."
step "Click 'Apply' — the first Docker build takes ~5-10 minutes."
step "On the service page, copy the public URL (top of the page)."
ask RENDER_URL "Paste the service URL (e.g. https://retail-decision-intelligence-agent.onrender.com):"
RENDER_URL="${RENDER_URL%/}"
[[ -n "$RENDER_URL" ]] && write_env RENDER_URL "$RENDER_URL"

# ── Stage 4: wait for the first deploy ─────────────────────────────────────
stage "Wait for the first deploy"
say "Polling $RENDER_URL/health until it answers (first build is slow)."
OK=0
for i in $(seq 1 72); do
  if curl -sf --max-time 10 "$RENDER_URL/health" > /dev/null 2>&1; then OK=1; break; fi
  sleep 10
done
if [[ $OK -eq 1 ]]; then
  printf '  %s✓ /health answered%s\n' "$GREEN" "$RESET"
else
  warn "/health never answered. Check the Render dashboard Events/Logs tab,"
  warn "fix, and re-run this wizard — it keeps values already saved."
  exit 1
fi

# ── Stage 5: verify the closed loop on the live URL ────────────────────────
stage "Verify the live agent"
step "GET /health — done above."
if curl -sf -H "Authorization: Bearer $TOKEN" "$RENDER_URL/metrics" | head -3; then
  say "↑ /metrics answers with the token."
else
  warn "/metrics did not answer with the token — check APPROVAL_AUTH_TOKEN."
fi
if confirm "Run one recommendation sweep on the live agent now?"; then
  curl -sf -X POST -H "Authorization: Bearer $TOKEN" "$RENDER_URL/recommendations/run" \
    | head -c 400 || warn "sweep failed — check the Render logs tab"
  printf '\n'
fi
if confirm "Walk approve → execute → reverse on the live agent?"; then
  curl -sf -H "Authorization: Bearer $TOKEN" "$RENDER_URL/pending-approvals" | head -c 300; printf '\n'
  read -r -p "  store_id to approve: " SID
  curl -sf -X POST -H "Authorization: Bearer $TOKEN" "$RENDER_URL/approve/$SID" | head -c 300; printf '\n'
  curl -sf -X POST -H "Authorization: Bearer $TOKEN" "$RENDER_URL/execute/$SID" | head -c 300; printf '\n'
  read -r -p "  execution_id to reverse: " EID
  curl -sf -X POST -H "Authorization: Bearer $TOKEN" "$RENDER_URL/executions/$EID/reverse" | head -c 300; printf '\n'
fi

# ── Stage 6: record the URL ─────────────────────────────────────────────────
stage "Record the live URL"
write_env RENDER_URL "$RENDER_URL"
say "Portfolio next step: add the URL to the README (under the deploy button)."
if confirm "Add 'Live demo: $RENDER_URL' to README.md and push it now?"; then
  if grep -q 'Live demo:' README.md; then
    sed -i "s|Live demo: .*|Live demo: [$RENDER_URL]($RENDER_URL) — always-on; write paths need a token.|" README.md
  else
    sed -i "/Deploy to Render/a\\\n\\\n**Live demo:** [$RENDER_URL]($RENDER_URL) — always-on; write paths need a token." README.md
  fi
  git add README.md && git commit -q -m "docs: live demo URL" && git push origin main \
    && printf '  %s✓ pushed%s\n' "$GREEN" "$RESET" \
    || warn "could not push automatically — commit README.md by hand"
fi

finish
